In [1]:
import numpy as np
my_array = np.array([[1,2], [3,4], [5,6], [7,8]], dtype=np.uint16)
print("The shape of the array is:", my_array.shape)
print("The number of dimensions of the array is:", my_array.ndim)
print("The size of the element in bytes is:", my_array.itemsize)

The shape of the array is: (4, 2)
The number of dimensions of the array is: 2
The size of the element in bytes is: 2


In [2]:
import numpy as np
arr = np.linspace(1, 10, 10)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [3]:
import numpy as np
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [4]:
import numpy as np
arr = np.arange(10)
print("Array:", arr)
print("Memory size of the array in bytes:", arr.nbytes)

Array: [0 1 2 3 4 5 6 7 8 9]
Memory size of the array in bytes: 80


In [11]:
import numpy as np
arr = np.arange(10)
reverse_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", reverse_arr)

Original array: [0 1 2 3 4 5 6 7 8 9]
Reversed array: [9 8 7 6 5 4 3 2 1 0]


In [12]:
import numpy as np
my_array = np .array([[1, 2], [3, 4], [5, 6], [7, 8]])
print("The shape of the array is:", my_array.shape)
print("The number of dimensions of the array is:", my_array.ndim)
print("The size of each element in bytes is:", my_array.itemsize)

The shape of the array is: (4, 2)
The number of dimensions of the array is: 2
The size of each element in bytes is: 8


In [16]:
import numpy as np
arr = np.arange(5,10)
print("Array:", arr[2:5])

Array: [7 8 9]


In [17]:
import numpy as np
arr = np.arange(5,10)
print("Array:", arr[2])

Array: 7


In [18]:
import numpy as np
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
import numpy as np
arr = np.arange(1,17).reshape(4,4)
print("Array:\n", arr)
first_row = arr[0]
print("First row:", first_row)
last_col = arr[:, -1]
print("Last column:", last_col)


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First row: [1 2 3 4]
Last column: [ 4  8 12 16]


In [21]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
extracted_elements = arr[2:8:2]
print("Extracted elements:", extracted_elements)

Extracted elements: [3 5 7]
